"""Add barangay_id to User model

Revision ID: b11a4d04a389
Revises: 
Create Date: 2025-12-01 10:09:45.887393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b11a4d04a389'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barangay_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_barangay_id', 'barangay', ['barangay_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_barangay_id', type_='foreignkey')
        batch_op.drop_column('barangay_id')

    # ### end Alembic commands ###
